### PR TITLE
Add project path hashing test cases

### PR DESCRIPTION
**Pull request by fmoor**
fix https://github.com/edgedb/shared-client-testcases/issues/4

### CODE REVIEW

**Comment by jaclarke** [comment]
I think these tests need to specify the homedir (or if we only want to test the hashing bit, then result could just be the `{name}-{hash}` part)

**Comment by fmoor** [comment]
> I think these tests need to specify the homedir.

added

**Review by jaclarke — APPROVED** [review]

**Comment by fmoor** [comment]
@jaclarke what do you think about using `configDir` in theses tests instead of the `homeDir`? On some platforms with certain environment variables set the config directory is completely independent of the home directory. This would make these tests fail on development machines set up this way.

**Comment by jaclarke** [comment]
I think the tests should have a consistent environment regardless of where they're run, so I think we should just override these env vars (I assume the issue is with env vars like `XDG_CONFIG_HOME`). We could also add testcases specifying these env vars, if we want to test config dir resolution more thoroughly as well.

**Pull request merged**
